/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as SubjectSharesBalanceContractJson } from "../SubjectSharesBalance.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SubjectSharesBalanceTypes {
  export type Fields = {
    subject: Address;
    subjectSharesContractId: HexString;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getBalance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  SubjectSharesBalanceInstance,
  SubjectSharesBalanceTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SubjectSharesBalanceTypes.Fields;
  }

  consts = {
    ErrorCodes: {
      SubjectSharesContractAllowedOnly: BigInt(0),
      NotEnoughBalance: BigInt(1),
    },
  };

  at(address: string): SubjectSharesBalanceInstance {
    return new SubjectSharesBalanceInstance(address);
  }

  tests = {
    getBalance: async (
      params: Omit<
        TestContractParams<SubjectSharesBalanceTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getBalance", params);
    },
    addBalance: async (
      params: TestContractParams<
        SubjectSharesBalanceTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "addBalance", params);
    },
    reduceBalance: async (
      params: TestContractParams<
        SubjectSharesBalanceTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "reduceBalance", params);
    },
  };
}

// Use this object to test and deploy the contract
export const SubjectSharesBalance = new Factory(
  Contract.fromJson(
    SubjectSharesBalanceContractJson,
    "",
    "3db400267b6d4ab5737e7daf05a152f31ed33b890a8579e5256531e1f5c7496a"
  )
);

// Use this class to interact with the blockchain
export class SubjectSharesBalanceInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SubjectSharesBalanceTypes.State> {
    return fetchContractState(SubjectSharesBalance, this);
  }

  methods = {
    getBalance: async (
      params?: SubjectSharesBalanceTypes.CallMethodParams<"getBalance">
    ): Promise<SubjectSharesBalanceTypes.CallMethodResult<"getBalance">> => {
      return callMethod(
        SubjectSharesBalance,
        this,
        "getBalance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends SubjectSharesBalanceTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SubjectSharesBalanceTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      SubjectSharesBalance,
      this,
      calls,
      getContractByCodeHash
    )) as SubjectSharesBalanceTypes.MultiCallResults<Calls>;
  }
}
