/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as YoutubeContractJson } from "../Youtube.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace YoutubeTypes {
  export type Fields = {
    name: HexString;
    symbol: HexString;
    decimals: bigint;
    supply: bigint;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type WithdrawEvent = ContractEvent<{ user: Address; amount: bigint }>;
  export type DepositEvent = ContractEvent<{ user: Address; amount: bigint }>;
  export type DevwithdrawEvent = ContractEvent<{
    user: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<YoutubeInstance, YoutubeTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as YoutubeTypes.Fields;
  }

  eventIndex = { Withdraw: 0, Deposit: 1, Devwithdraw: 2 };
  consts = { ErrorCodes: { Invalidamount: BigInt(2) } };

  at(address: string): YoutubeInstance {
    return new YoutubeInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<TestContractParams<YoutubeTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<TestContractParams<YoutubeTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<TestContractParams<YoutubeTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<TestContractParams<YoutubeTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    withdraw: async (
      params: TestContractParams<YoutubeTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
    deposit: async (
      params: TestContractParams<YoutubeTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "deposit", params);
    },
    devwithdraw: async (
      params: TestContractParams<YoutubeTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "devwithdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const Youtube = new Factory(
  Contract.fromJson(
    YoutubeContractJson,
    "",
    "38d751f3d5ef35debdc44152f60ff4d733bb00f756e1285ce0cb3c8de349a7e1"
  )
);

// Use this class to interact with the blockchain
export class YoutubeInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<YoutubeTypes.State> {
    return fetchContractState(Youtube, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<YoutubeTypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Youtube.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  subscribeDepositEvent(
    options: EventSubscribeOptions<YoutubeTypes.DepositEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Youtube.contract,
      this,
      options,
      "Deposit",
      fromCount
    );
  }

  subscribeDevwithdrawEvent(
    options: EventSubscribeOptions<YoutubeTypes.DevwithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Youtube.contract,
      this,
      options,
      "Devwithdraw",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | YoutubeTypes.WithdrawEvent
      | YoutubeTypes.DepositEvent
      | YoutubeTypes.DevwithdrawEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(Youtube.contract, this, options, fromCount);
  }

  methods = {
    getSymbol: async (
      params?: YoutubeTypes.CallMethodParams<"getSymbol">
    ): Promise<YoutubeTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        Youtube,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: YoutubeTypes.CallMethodParams<"getName">
    ): Promise<YoutubeTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Youtube,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: YoutubeTypes.CallMethodParams<"getDecimals">
    ): Promise<YoutubeTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        Youtube,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: YoutubeTypes.CallMethodParams<"getTotalSupply">
    ): Promise<YoutubeTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        Youtube,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends YoutubeTypes.MultiCallParams>(
    calls: Calls
  ): Promise<YoutubeTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      Youtube,
      this,
      calls,
      getContractByCodeHash
    )) as YoutubeTypes.MultiCallResults<Calls>;
  }
}
