import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { TokenDapp } from '@/components/TokenDapp'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'

import { tokenFaucetConfig } from '@/services/utils'
import { LendingDapp} from '@/components/LendingDapp'


export default function Home() {

      const { connectionStatus, account } = useWallet();

  return (
    <>
      <div className={styles.container}>
        <AlephiumConnectButton />
        {!!account && <div> <h1>Address of Wallet</h1> {account.address} </div> }

        <Head>
          <title>Token Faucet</title>
          <meta name="description" content="Generated by @alephium/cli init" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {connectionStatus === 'connected' && (
          <TokenDapp config={tokenFaucetConfig} />
        )}
          <LendingDapp config={tokenFaucetConfig}/>
      </div>
    </>
  )
}
